---
inventory:
  plugin: SimpleInventory
  options:
    host_file: /app/inventory/hosts.yaml
    group_file: /app/inventory/groups.yaml
    defaults_file: /app/inventory/defaults.yaml

runner:
  plugin: threaded
  options:
    num_workers: 10

logging:
  enabled: false
